### ISSUE TITLE
Could not find "/var/folders..." in any of your source paths

### ISSUE THREAD

**Issue by jmccaffrey** [patshaughnessy/scaffoldhub#1]
I bet I missed a step somewhere, but here's what I did.
1. listen to ruby5...exclaim "wow, scaffoldhub sounds awesome" loudly
2.  create new rails project
3. add gem 'scaffoldhub' to Gemfile
4. bundle install
5. scaffoldhub infinitescroll person name:string age:integer
   
   invoke  active_record
     download    http://www.scaffoldhub.org/scaffolds/infinitescroll/spec
     download    https://raw.github.com/alexrothenberg/infinitescroll_scaffold/master/templates/migration.rb
   Could not find "/var/folders/3B/3BxYeyNUFGCDdNZoz7Colk+++TI/-Tmp-/migration.rb20110610-99376-gqyxmt" in any of your source paths.

I tried different versions of rails 3, different rvm setups for 1.9, etc.
I see that there is a /var/folders/3B/3BxYeyNUFGCDdNZoz7Colk+++TI/-Tmp-/ directory, but that file is not in it.

**Comment by patshaughnessy** [comment]
Hmm - I can't reproduce this, with Ruby 1.9.2, 1.9.1 or 1.8.7. Can you tell me which versions of Ruby and Rails you are using? ... allthough it sounds like it doesn't matter.

**Comment by jmccaffrey** [comment]
well, its good to know that its not some obvious step that I missed. Maybe there is a permissions problem on a directory or something. I was gonna look through the code to see what is happening, (is there a verbose mode?) and maybe try it on a different machine.

I have the 0.1.1 which is what you get from bundle install. I can try to pull down the latest code and build the gem with the recent changes.

**Comment by patshaughnessy** [comment]
Yea you're doing everything correctly. And you have the latest gem code... I haven't made any changes since pushing version 0.1.1.

I actually did reproduce the problem once or twice in the last few minutes, but now it's working again for me. It seems to be an intermittent problem with Tempfile; the gem downloads the ERB templates to temp files, but for you they are deleted before they can be used by the generators.

Let me dig into this deeper and see if I can find a way to reliably reproduce the issue.

Thanks for letting me know about this! Sorry it's not working.

**Comment by patshaughnessy** [comment]
Ok - I think I have a fix. The mistake had to do with using Tempfile, but not calling "close". This leads to the file being deleted at a random time depending on when the Ruby GC runs.

I'll do some more careful testing, post the fix and let you know when to try again... might be tonight or tomorrow morning.

Thanks so much for the positive feedback! I hope we can get this working on your machine soon!

**Comment by jmccaffrey** [comment]
not sure if this will help, but I have no-atime modifier set on my drive, which means that the os doesn't update the access-time of the file when it is read. I don't know if that would affect things, but I'm throwing it out there.

I also have a seagate momentus hybrid drive with is a regular hd fronted by a 4gb SSD. 
I haven't run into any other problems with this setup (its sped up my tests across several projects), and I have lots of rails projects on lots of versions of ruby and rails. (well, ok. I have maybe 25 different projects that I've run on this setup, 10 of which are active day to day)

Maybe there is something about my setup that exacerbates the tempfile problem.  I would be interesting to know if anyone else has this same problem

**Comment by patshaughnessy** [comment]
I suspect the problem was just I wasn't calling Tempfile.close...  I added that now and tested in various versions of Rails and Ruby.

Can you update the scaffoldhub gem in your app to v0.1.2 and try again? Please let me know if it works or not. If not, I'll have to look into the atime setting you have mentioned.

**Comment by jmccaffrey** [comment]
Success!

Thanks Pat, I look forward to trying out these scaffolds and contributing some of my own. Thanks for putting this project together. I think it will be a great way for people to learn more, and share great code.

It would be cool to track how many downloads there are of each scaffold type, to get a sense of popularity, etc. (ha, scope creep!)

**Comment by patshaughnessy** [comment]
Awesome! Thanks a lot for reporting and helping me test this issue...and for all the positive feedback :)

Yup I'm already tracking download metrics, and plan to display that on the site soon, once there's some significant data.

Can't wait to see your first scaffold! Let me know if you have questions on the scaffold authoring process.
